app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/



Route::auth();




// Ticket Route
Route::group(['middleware' => 'auth'], function() {

    Route::get('/', 'HomeController@index');

    Route::get('/homepage-2', 'HomeController@homepage2');
    Route::get('/it-policy',function (){
        return view('pdf');
    });
    Route::post('create-leads', [
        'as' => 'create.lead',
        'uses' => 'LeadController@createLead'
    ]);
    Route::get('all-leads', [
        'as' => 'all.leads',
        'uses' => 'LeadController@allLeads'
    ]);
    Route::get('edit-lead/{id}', [
        'as' => 'edit.lead',
        'uses' => 'LeadController@getEditLeads'
    ]);
    Route::post('edit-leads/{id}', [
        'as' => 'edit.post.lead',
        'uses' => 'LeadController@postEditLeads'
    ]);
    Route::post('/lead/remove', [
        'as'	=> 	'dashboard.lead.remove',
        'uses'	=> 	'Backend\LeadController@removeLead',
    ]);
    // Lead remove
    Route::post('/lead/remove', [
        'as'	=> 	'dashboard.lead.remove',
        'uses'	=> 	'Backend\TicketController@removeLead',
    ]);

    // test mail
    Route::get('/testmail', 'HomeController@testmail');
	Route::post('create-tickets', [
		'as' => 'create.ticket', 
		'uses' => 'TicketController@createTicket'
	]);

	Route::get('edit-ticket/{id}', [
		'as' => 'edit.ticket', 
		'uses' => 'TicketController@getEditTickets'
	]);

	Route::post('edit-tickets/{id}', [
		'as' => 'edit.post.ticket', 
		'uses' => 'TicketController@postEditTickets'
	]);

	Route::get('all-tickets', [
		'as' => 'all.tickets', 
		'uses' => 'TicketController@allTickets'
	]);

	Route::get('ticket/{id}/{subject}', [
		'as' => 'single.ticket', 
		'uses' => 'TicketController@showTickets'
	]);

	// Ticket remove
	Route::post('/ticket/remove', [
		'as'	=> 	'dashboard.ticket.remove',
		'uses'	=> 	'Backend\TicketController@removeTicket',
	]);
    // get  subjects
    Route::get('/get/subjects', [
        'as'	=> 	'get.subjects',
        'uses'	=> 	'HomeController@getSubjects',
    ]);
});


// Reply Route
Route::group(['middleware' => 'auth'], function() {

	Route::post('{id}/create-reply', [
		'as' => 'create.reply', 
		'uses' => 'ReplyController@createReply'
	]);

	Route::post('/remove-reply/{id}', [
		'as' => 'remove.reply', 
		'uses' => 'ReplyController@removeReply'
	]);

});

// Profile Settings
Route::group(['middleware' => 'auth'], function() {

	Route::get('profile/settings', [
		'as' => 'proifle.settings', 
		'uses' => 'HomeController@settings'
	]);

	 // Update profile
	Route::post('/profile/update', [
		'as'	=> 	'profile.update',
		'uses'	=> 	'Backend\SettingsController@profileUpdate',
	]);


});

//////////////////////
// Dashboard Routes //
//////////////////////
Route::group(['prefix' => 'dashboard', 'middleware' => ['auth', 'role:admin|staff'], 'namespace' => 'Backend'], function() {

	Route::get('/', [
		'as' => 'dashboard.index', 
		'uses' => 'DashboardController@index'
	]);

	Route::post('/get-authenticated-user', [
		'as' => 'get.auth.user', 
		'uses' => 'DashboardController@getAuthUser'
	]);
    /////////////////////////////
    // Dashboard Message Routes //
    /////////////////////////////
    Route::get('all-messages', [
        'as' => 'dashboard.all.messages',
        'uses' => 'MessageController@allMessages'
    ]);
    // Ticket remove
    Route::post('/message/remove', [
        'as'	=> 	'dashboard.message.remove',
        'uses'	=> 	'MessageController@removeMessage',
    ]);
    Route::post('/message/create', [
        'as'	=> 	'dashboard.message.create',
        'uses'	=> 	'MessageController@create',
    ]);
	/////////////////////////////
	// Dashboard Ticket Routes //
	/////////////////////////////
    Route::get('/tickets/tdata', [
        'as'	=> 	'dashboard.tickets.tdata',
        'uses'	=> 	'TicketController@tdata',
    ]);
    Route::get('/tickets/home', [
        'as'	=> 	'dashboard.tickets.home',
        'uses'	=> 	'TicketController@home',
    ]);
    Route::get('/tickets/report', [
        'as' => 'dashboard.tickets.report',
        'uses' => 'TicketController@report'
    ]);
    Route::get('/tickets/reportTdata', [
        'as'	=> 	'dashboard.tickets.reportTdata',
        'uses'	=> 	'TicketController@reportTdata',
    ]);
	Route::get('/tickets/{view}', [
		'as'	=> 	'dashboard.tickets',
		'uses'	=> 	'TicketController@tickets',
	]);


    Route::get('/tickets', function() {
		return redirect('/dashboard/tickets/all');
	});

	Route::get('/tickets/{id}/{subject}', [
		'as' => 'dashboard.single.ticket', 
		'uses' => 'TicketController@showTickets'
	]);

	// assign ticket to staff
	Route::post('/assign/ticket/{id}', [
		'as'	=> 	'ticket.assign.user',
		'uses'	=> 	'TicketController@assignTicket',
	]);

	// update ticket status
	Route::post('/update/ticket/{id}/status', [
		'as'	=> 	'update.ticket.status',
		'uses'	=> 	'TicketController@updateStatus',
	]);



	// Ticket search
	Route::get('/ticket/search', [
		'as'	=> 	'dashboard.ticket.search',
		'uses'	=> 	'TicketController@searchTicket',
	]);


	///////////////////////////////////
	// Dashboard Noticiations Routes //
	///////////////////////////////////

	// Remove single notification

	Route::post('/remove/single/notification', [
		'as'	=> 	'remove.single.notification',
		'uses'	=> 	'NotificationController@removeNotif',
	]);

	// Remove all notification
	Route::post('/remove/all/notification', [
		'as'	=> 	'remove.all.notification',
		'uses'	=> 	'NotificationController@removeAllNotif',
	]);

    ///////////////////////////////////////
    // Dashboard Reports route           //
    ///////////////////////////////////////
    Route::get('/reports/my-stats', [
        'as'	=> 	'dashboard.reports.mystats',
        'uses'	=> 	'ReportsController@mystats',
    ]);
    Route::get('/reports/mystats-tdata', [
        'as'	=> 	'dashboard.reports.mystats_tdata',
        'uses'	=> 	'ReportsController@mystats_tdata',
    ]);
    Route::get('/reports/department-vs-tickets', [
        'as'	=> 	'dashboard.reports.depvstkt',
        'uses'	=> 	'ReportsController@depvstkt',
    ]);
    Route::get('/reports/department-vs-tickets-tdata', [
        'as'	=> 	'dashboard.reports.depvstkt_tdata',
        'uses'	=> 	'ReportsController@depvstkt_tdata',
    ]);
    Route::get('/reports/client-vs-tickets', [
        'as'	=> 	'dashboard.reports.clientvstkt',
        'uses'	=> 	'ReportsController@clientvstkt',
    ]);
    Route::get('/reports/client-vs-tickets-tdata', [
        'as'	=> 	'dashboard.reports.clientvstkt_tdata',
        'uses'	=> 	'ReportsController@clientvstkt_tdata',
    ]);
    Route::get('/reports/user-vs-tickets', [
        'as'	=> 	'dashboard.reports.uservstkt',
        'uses'	=> 	'ReportsController@uservstkt',
    ]);
    Route::get('/reports/user-vs-tickets-tdata', [
        'as'	=> 	'dashboard.reports.uservstkt_tdata',
        'uses'	=> 	'ReportsController@uservstkt_tdata',
    ]);
    Route::get('/reports/location-vs-tickets', [
        'as'	=> 	'dashboard.reports.locationvstkt',
        'uses'	=> 	'ReportsController@locationvstkt',
    ]);
    Route::get('/reports/location-vs-tickets-tdata', [
        'as'	=> 	'dashboard.reports.locationvstkt_tdata',
        'uses'	=> 	'ReportsController@locationvstkt_tdata',
    ]);
    Route::get('/reports/location-vs-deptickets', [
        'as'	=> 	'dashboard.reports.locationvsdeptkt',
        'uses'	=> 	'ReportsController@locationvsdeptkt',
    ]);
    Route::get('/reports/location-vs-deptickets-tdata', [
        'as'	=> 	'dashboard.reports.locationvsdeptkt_tdata',
        'uses'	=> 	'ReportsController@locationvsdeptkt_tdata',
    ]);
    Route::get('/reports/common', [
        'as'	=> 	'dashboard.reports.commonreport',
        'uses'	=> 	'ReportsController@commonreport',
    ]);
    Route::get('/reports/common-tdata', [
        'as'	=> 	'dashboard.reports.commonreport_tdata',
        'uses'	=> 	'ReportsController@commonreport_tdata',
    ]);
    Route::get('/reports/common-chart-data', [
        'as'	=> 	'dashboard.reports.commonchart_tdata',
        'uses'	=> 	'ReportsController@commonchart_tdata',
    ]);
	///////////////////////////////////////
	// Dashboard Staff and Clients route //
	///////////////////////////////////////


	// Dashbaord Staffs
	Route::get('/staffs/all', [
		'as'	=> 	'dashboard.staffs.all',
		'uses'	=> 	'StaffController@allStaffs',
	]);

	// Staff create
	Route::get('/staffs/create', [
		'as'	=> 	'dashboard.staffs.create',
		'uses'	=> 	'StaffController@getCreate',
	]);

	// Staff Create
	Route::post('/staffs/create', [
		'as'	=> 	'dashboard.staffs.postCreate',
		'uses'	=> 	'StaffController@create',
	]);

	// Get staff edit ajax result
	Route::post('/staffs/edit', [
		'as'	=> 	'dashboard.staffs.getEdit',
		'uses'	=> 	'StaffController@getEdit',
	]);

	// Staff Update
	Route::post('/staffs/update', [
		'as'	=> 	'dashboard.staffs.update',
		'uses'	=> 	'StaffController@update',
	]);

	// Get Staff edit page
	Route::get('/staffs/get-edit/{id}', [
		'as'	=> 	'dashboard.staffs.getPageEdit',
		'uses'	=> 	'StaffController@getPageEdit',
	]);


	// Staff Remove
	Route::post('/staffs/remove', [
		'as'	=> 	'dashboard.staffs.remove',
		'uses'	=> 	'StaffController@removeStaff',
	]);

	// Dashbaord Clients
	Route::get('/clients/all', [
		'as'	=> 	'dashboard.clients.all',
		'uses'	=> 	'ClientController@allClients',
	])->middleware('staffPermission');

	Route::post('/clients/create', [
		'as'	=> 	'dashboard.clients.create',
		'uses'	=> 	'ClientController@create',
	]);
    Route::post('/clients/edit', [
        'as'	=> 	'dashboard.clients.edit',
        'uses'	=> 	'ClientController@edit',
    ]);
	Route::post('/clients/remove', [

app/Models/Ticket.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Models\User;
use App\Models\Reply;
use App\Models\Department;


class Ticket extends Model
{
    protected $fillable = ['user_id', 'department_id', 'subject', 'message', 'location'];


    /**
     *
     * Ticket belongs to the user
     * @return App\Models\User
     *
     */
    public  function user()
    {
        return $this->belongsTo(User::class);
    }
    /**
     *
     * Ticket has a assigned user
     * @return App\Models\User
     *
     */
    public  function assignedTo()
    {
        return $this->belongsTo(User::class,'assigned_to');
    }

    /**
     *
     * Ticket has many replies
     * @return App\Models\Reply
     *
     */
    public function replies()
    {
        return $this->hasMany(Reply::class);
    }



    /**
     *
     * Ticket belongs to the department
     * @return App\Models\Department
     *
     */
    public function department()
    {
        return $this->belongsTo(Department::class);
    }


    /**
     *
     * Get the department name
     * @return App\Models\Department
     * 
     *
     */
    public function getDepartment(  )
    {   
        $department =  $this->attributes['department_id'];

        if( $department ) {
            return $this->department->name;
        } else {
            return 'No department.';
        }
    }

    /**
     *
     * Format the subject
     * @return string
     *
     */
    public function FormatSubject(  )
    {   
        $value =  $this->attributes['subject'];

        return str_replace(' ', '-', $value);
    }


    /**
     *
     * Reformat the subject
     * @param $subject
     * @return string
     *
     */
    public static function reformatTicket( $subject )
    {   
        return str_replace('-', ' ', $subject);
    }



    /**
     *
     * Get the assigned user
     * @return App\Models\User
     *
     */
    public function getAssignedStaff()
    {
        $assigned_to = $this->attributes['assigned_to'];

        if( $assigned_to == 0) {
            return trans('messages.singleTicket.notAssignedYet');
        } else {
            $user = User::find($assigned_to);

            if( $user ) {
                return $user->fullName() ;
            }
        }
    }

    /**
     *
     * Get the assigned user
     * @return App\Models\User
     *
     */
    public function getSolvedBy()
    {
        $solved_by = $this->attributes['solved_by'];

        if( $solved_by == 0) {
            return 'Not solved yet.';
        } else {
            $user = User::find($solved_by);

            if( $user ) {
                return $user->fullName();
            }
        }
    }


}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Models\Role;
use App\Models\Ticket;
use App\Models\Visitor;
use App\Models\Department;
use App\Http\Requests;
use App\Http\Controllers\AppBaseController;

class DashboardController extends AppBaseController
{

    /**
     *
     * @param  App\Models\Visitor
     * @return void
     * 
     */
    function __construct(Visitor $visitors)
    {
        parent::__construct();

        $this->visitors = $visitors;
    }



    /**
     *
     * Dashboard Page
     * @return App\Models\Ticket
     */
    public function index()
    {   
        // Get only 7 tickets for the dashboard
        $tickets = Ticket::take(7)->orderBy('created_at', 'DESC')->get();

        // Ticket Counting
        $all_ticket_counting = Ticket::count();
        $new_ticket_counting = Ticket::where('status', 'new')->count();
        //$my_ticket_counting = Ticket::where('assigned_to', Auth::user()->id)->count();
        $pending_ticket_counting = Ticket::where('status', 'pending')->count();
        $solved_ticket_counting = Ticket::where('status', 'solved')->count();

        // Get clients
        $role = Role::where('name', 'client')->first();
        $clients = Role::find($role->id)->users()->orderBy('created_at', 'DESC')->take(6)->get();

        // Get staffs
        $role = Role::where('name', 'staff')->first();
        $staffs = Role::find($role->id)->users()->orderBy('created_at', 'DESC')->take(10)->get();

      //  $departments = Department::lists('name', 'id');
        $departments = Department::all(['id', 'name']);
        // $visitors = $this->visitors->all();
        // $clients = $this->visitors->whereMonth('created_at', '=', date('m'))->where('type', 'client')->get();
        // $visitors = $this->visitors->whereMonth('created_at', '=', date('m'))->where('type', 'guest')->get();

        $data = compact( 'tickets', 'departments', 'my_ticket_counting', 'all_ticket_counting', 'new_ticket_counting','pending_ticket_counting', 'solved_ticket_counting', 'clients', 'staffs');

        return view('dashboard.home', $data);
    }



    /**
     *
     * Return the authenticated user as JSON
     * @return App\Models\User
     */
    public function getAuthUser()
    {
        if( \Auth::check() ) {
            $user = \Auth::user();

            return \Response::json(['user' => $user]);
        }

    }
}

resources/views/partials/dashboard/statistics.blade.php
<script>
    {!! 'var departments='.$departments.';' !!}
    function drawCountryVsSubject(json) {
        $('#barchart').html('');
        var chartType=$('#chart option:selected');
        $('#chartTitle').text(chartType.text());
        var location=$('#location option:selected').text();
        var month=$('#month option:selected').text();

        var xAxisData=[];
        var dataSeries=[];
        var dataZero=[];
        $.each(departments, function(index, value) {
            xAxisData.push(value.name);
            dataZero.push(0);
        });


        $.each(json, function(index, countryData) {
            var showLegend=undefined;
            var marginTop=50;
            var titleY=20;
            if(index=='Katunayake'){
                showLegend=true;
                marginTop=175;
                titleY=130;
            }

            $('<div class="chart">')
                .appendTo('#barchart')
                .highcharts({
                    chart: {
                        marginTop: marginTop,
                        type: 'column',

                    },
                    title: {
                        align: 'left',
                        x: 100,
                        y: titleY,
                        text: '('+index+''+month+')'
                    },
                    xAxis: {
                        categories: xAxisData
                    },
                    yAxis: {
                        min: 0,
                        title: {
                            text: 'Total Tickets'
                        }
                    },
                    legend: {
                        floating: true,
                        enabled: showLegend,
                        verticalAlign: 'top',

                        itemWidth: 160,
                        itemStyle: {
                            'font-size': '10px'
                        }
                    },
                    plotOptions: {

                    },
                    series: countryData
                });

        });





    }
$(document).ready(function() {
    $.getJSON("/dashboard/reports/common-chart-data", null, function(data) {

        drawCountryVsSubject(data)
    });

  });
</script>

resources/views/partials/dashboard/ticket_information.blade.php
<!-- TICKET INFORMATAION -->
<div class="col-lg-4 col-md-12 ticket-information">
    <div class="ticket-box">
        <div class="ticket-header">
            <h4>Ticket information</h4>
        </div>
        <div class="ticket-info-body">
            <table class="table table-hover">
                <tr>
                    <th> {{ trans('messages.singleTicket.ticketID') }}</th>
                    <td>#{{ $ticket->id }}</td>
                </tr>
                <tr>
                    <th>{{ trans('messages.singleTicket.client') }}:</th>
                    <td>{{ $ticket->user->fullName() }}</td>
                </tr>
                <tr>
                    <th>{{ trans('messages.singleTicket.supportType') }}</th>
                    <td>{{ $ticket->getDepartment() }}</td>
                </tr>
                <tr>
                    <th>{{ trans('messages.singleTicket.ticketStatus') }}</th>
                    <td class="template-ticket-status"><span class="status-{{ $ticket->status }} ">{{ ucwords($ticket->status) }}</span></td>
                </tr>
                <tr>
                    <th>{{ trans('messages.singleTicket.assignedTicket') }}</th>
                    <td  class=" ticket-info-assigned-staff"> {{ $ticket->getAssignedStaff() }} </td>
                </tr>
                @if( $ticket->solved_by )
                    <tr class="solved_by_staff">
                        <th>{{ trans('messages.singleTicket.solvedBy') }}</th>
                        <td  class=" ticket-info-solved-staff"> {{ $ticket->getSolvedBy() }} </td>
                    </tr>
                @endif
                <tr>
                    <th>Created At</th>
                    <td  class=" ticket-info-assigned-staff"> {{ $ticket->created_at }} </td>
                </tr>
                <tr>
                    <th>Updated At</th>
                    <td  class=" ticket-info-assigned-staff"> {{ $ticket->updated_at }} </td>
                </tr>
            </table>
        </div>
        <div class="ticket-info-footer">
            <div class="ticket-info-buttons">
                <div class="as-n-s">
                    <button data-modal="modal-5" class="btn btn-info assign-new-trigger">{{ trans('messages.singleTicket.assignNewTicket') }}</button>
                    
                    <div class="assign-staff-up-box up-info-box ">
                        <h3>{{ trans('messages.singleTicket.assignThisTicket') }}</h3>
                        <span class="up-box-cancel"><i class="fa fa-times"></i></span>
                        
                        <span class="up-box-status assign_upbox"><i class="fa fa-circle-o-notch status-success"></i></span>

                        <!-- ASSIGN TICKET POPUP TO ASSIGN THIS TICKET TO STAFF -->
                        <div class="box-form-outer scrollbar">
                            {{ Form::open([
                                'route' => ['ticket.assign.user', $ticket->id], 
                                'method' => 'post', 
                                'id' => 'ticket_assign_user'
                            ]) }}

                                @if( count($staffs) )

                                    @foreach($staffs as $staff)

                                        <!-- EACH STAFF IN THE LIST -->
                                        <div class="media assign-user-media">
                                            <label for="assign_user_{{ $staff->id }}">

                                              <div class="media-left">
                                                  <img class="media-object" src="{{ $staff->profileImg(40) }}" alt="Pic">
                                              </div>
                                              <div class="media-body">
                                                <h4 class="media-heading">{{ $staff->fullName() }}</h4>
                                                <p>{{ $staff->role_name }}</p>
                                                <div>
                                                    <input 
                                                        type="radio" 
                                                        name="assign_user" 
                                                        class="assign_user" 
                                                        value="{{ $staff->id }}" 
                                                        id="assign_user_{{ $staff->id }}"
                                                        {{ $staff->fullName() == $ticket->getAssignedStaff() ? 'checked' : '' }}
                                                    >
                                                    <span class="input_radio"><i class="fa fa-check"></i></span>
                                                </div>
                                              </div>
                                            </label>
                                        </div>
                                    @endforeach

                                @else
                                    <div class="media">
                                        <label for="assign_user_none">

                                          <div class="media-body">
                                            <h4 class="media-heading">{{ trans('messages.singleTicket.noStaffsFound') }}</h4>
                                          </div>

                                        </label>
                                    </div>
                                @endif


                            </form>
                        </div>
                    </div>
                </div>

                <div class="as-n-u">
                    <button class="btn btn-success update_status_trigger">{{ trans('messages.singleTicket.updateStatus') }}</button>                                            

                    <div class="up-info-box update-status">
                        <h3>{{ trans('messages.singleTicket.updateTicketStatus') }}</h3>
                        <span class="up-box-cancel"><i class="fa fa-times"></i></span>
                        <span class="up-box-status statusUpBx"><i class="fa fa-circle-o-notch fa-spin status-success"></i></span>

                        <!-- UPDATE TICKET STATUS POPUP -->
                        <div class="box-form-outer">                                                    
                            {{ Form::open([
                                'route' => ['update.ticket.status', $ticket->id],
                                'method' => 'post',
                                'id' => 'ticket_assign_form'
                            ])}}

                                <!-- UPDATE STATUS LIST -->
                                <div class="media">
                                    <label for="ticket_status_solved">

                                      <div class="media-body">
                                        <h4 class="media-heading">{{ trans('messages.singleTicket.solved') }}</h4>
                                        <div>
                                            <input 
                                                type="radio" 
                                                name="ticket_status" 
                                                class="ticket_status {{ $ticket->status == 'solved' ? 'checked' : '' }} " 
                                                value="solved" 
                                                id="ticket_status_solved"
                                                {{ $ticket->status == 'solved' ? 'checked' : '' }}
                                            >
                                            <span class="input_radio"></span>
                                        </div>
                                      </div>
                                    </label>
                                </div>

                                    <!-- UPDATE STATUS LIST -->
                                <div class="media">
                                    <label for="ticket_status_pending">

                                      <div class="media-body">
                                        <h4 class="media-heading">{{ trans('messages.singleTicket.pending') }}</h4>
                                        <div>
                                            <input 
                                                type="radio" 
                                                name="ticket_status" 
                                                class="ticket_status {{ $ticket->status == 'pending' ? 'checked' : '' }}" 
                                                value="pending" 
                                                id="ticket_status_pending"
                                                {{ $ticket->status == 'pending' ? 'checked' : '' }}
                                            >
                                            <span class="input_radio ticket_pending"></span>
                                        </div>
                                      </div>
                                    </label>
                                </div>

                            {{ Form::close() }}
                        </div>
                    </div>
                </div>
            </div>
        </div>


    </div>
</div>